#! /bin/bash

alias dnn='dotnet new'
alias dnr='dotnet run'
alias dnb='dotnet build'
alias dnt='dotnet test'
alias dnw='dotnet watch'
alias dnwr='dotnet watch run'
alias dns='dotnet sln'
alias dna='dotnet add'
alias dnp='dotnet pack'
alias dnng='dotnet nuget'