#!/bin/bash

alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias home='cd ~'
alias dev='cd ~/dev'
alias dot='cd ~/.dotfiles'
alias play='cd ~/dev/playground'

alias md='mkdir'

function mcd() {
    mkdir $1
    cd $1
}