#!/bin/bash

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias home='cd ~'
alias dev='cd ~/dev'
alias dot='cd ~/.dotfiles'
alias play='cd ~/dev/playground'

alias md='mkdir'